spring:
  application:
    name: rokcetmq-application
server:
  port: 8080

rocketmq:
  name-server: 117.50.66.184:9876
  producer:
    group: learnRokcetMQProducerGroup

mq:
  consumer:
    group: learnRocketMqTopicConsumer
    topic: LearnRocketMqTopic
  producer:
    topic: LearnRocketMqTopic
    message:
      tag: learn


